[metadata]
name = nextsound
version = 0.1.1
description = Turn an Ubuntu computer into a Bluetooth A2DP speaker
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
license_files = LICENSE
author = Made by TrungCao
classifiers =
    Development Status :: 3 - Alpha
    Environment :: X11 Applications :: GTK
    License :: OSI Approved :: MIT License
    Operating System :: POSIX :: Linux
    Programming Language :: Python :: 3

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.10
include_package_data = True

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
    nextsound = nextsound.__main__:main
    nextsound-doctor = nextsound.doctor:main
